[package]
name = "catan-agent"
version = "0.1.0"
authors = ["Declan Kelly <dkelly.home@gmail.com>"]

[[bin]]
name = "catan_agent"
path = "src/main.rs"

[dependencies]
rand = "0.3"
piston_window = "0.71.1"
find_folder = "0.3.0"