[package]
name = "catan-protocols"
version = "0.1.0"
authors = ["Declan Kelly <dkelly.home@gmail.com>"]
build = "build.rs"

[dependencies]
bytes = "~0.4.5"
prost = "~0.2.3"
prost-derive = "~0.2.3"

[build-dependencies]
prost-build = "~0.2.3"
glob = "0.2.11"