[package]
name = "catan_core"
version = "0.1.0"

[dependencies]
rand = "~0.3.16"
log = "~0.3.8"

uuid = { version = "~0.5.1", features = ["serde", "v4"] }

serde = "~1.0.15"
serde_derive = "~1.0.15"
serde_json = "~1.0.4"

tokio-core = "~0.1.10"
byteorder = "~1.1.0" 